name: Robowoofy dispatch command
on:
  workflow_dispatch:
    inputs:
      comment-id:
        description: 'The comment-id of the slash command'
        required: true
      file:
        description: 'The file to run (e.g. main, hydrate_ci_cache)'
        required: true
        default: 'main'
      network:
        description: 'The network (e.g. eth, bsc, matic, ftm)'
        required: true
        default: 'eth'
      fn:
        description: 'Brownie function to run'
        required: true
      send:
        description: 'Set to true to sign the tx and send to gnosis'
        required: false
        default: 'false'
      pull_request_number:
        description: 'Set to the pull request number for this command dispatch'
        required: true
      delete-branch-after-send:
        description: 'Set to true to delete the PR branch after running with send=true'
        default: 'true'
      pull_request_title:
        required: true
      pull_request_author:
        required: false
      pull_request_description:
        default: 'Empty PR description 🤡'

jobs:
  dispatchCommand:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: hmarr/debug-action@v2

    - uses: actions/checkout@v1
      with:
        ref: ${{ github.event.inputs.ref }}
    
    - uses: listonjesse/multisig-actions@0.0.2
      with:
        comment-id: ${{ github.event.inputs.comment-id }}
        file: ${{ github.event.inputs.file }}
        network: ${{ github.event.inputs.network }}
        fn: ${{ github.event.inputs.fn }}
        send: ${{ github.event.inputs.send }}
        pull_request_number: ${{ github.event.inputs.pull_request_number }}
        delete-branch-after-send: ${{ github.event.inputs.delete-branch-after-send }}
        pull_request_title: ${{ github.event.inputs.pull_request_title }}
        pull_request_author: ${{ github.event.inputs.pull_request_author }}
        pull_request_description: ${{ github.event.inputs.pull_request_description }}